name: Docker API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/minvectordb:latest .

    - name: Run Docker container
      run: docker run -d --name minvectordb -p 5403:7637 ghcr.io/${{ github.repository }}/minvectordb:latest

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest numba torch
        $reqFile = "requirements.txt"
        if (Test-Path $reqFile) { pip install -r $reqFile }

    - name: Run tests
      run: pytest tests/docker_tests/

    - name: Cleanup
      if: always()
      run: docker stop minvectordb && docker rm minvectordb
